# Generated by Django 6.0 on 2026-01-02 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, null=True)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('source', models.CharField(max_length=200)),
                ('article_url', models.URLField(unique=True)),
                ('published_at', models.DateTimeField()),
            ],
        ),
    ]
