# Generated by Django 6.0 on 2026-01-03 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_article_category_alter_article_source_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='source',
        ),
        migrations.AddField(
            model_name='article',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('technology', 'Technology'), ('politics', 'Politics'), ('sports', 'Sports'), ('entertainment', 'Entertainment')], default='general', max_length=20),
        ),
    ]
