# Generated by Django 6.0 on 2026-01-03 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_article_source_article_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('technology', 'Technology'), ('politics', 'Politics'), ('sports', 'Sports'), ('business', 'Business'), ('entertainment', 'Entertainment')], default='general', max_length=20),
        ),
    ]
